# serverless-compose.yml
services:
  authorization-service:
    path: authorization-service

  product-service:
    path: product-service

  import-service:
    path: import-service
    params:
      queueUrl: ${product-service.queueUrl}
      queueName: ${product-service.queueName}

